//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class AffiliationsSection
    {
        /// <summary>
        /// rptAffiliations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAffiliations;

        /// <summary>
        /// pnlNoAffiliations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAffiliations;
    }
}
