//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class EducationSection
    {
        /// <summary>
        /// rptEducation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptEducation;

        /// <summary>
        /// pnlNoEducation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoEducation;
    }
}
