//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class HeroSection
    {
        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// rowBirthday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowBirthday;

        /// <summary>
        /// litBirthday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBirthday;

        /// <summary>
        /// rowAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowAddress;

        /// <summary>
        /// litAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAddress;

        /// <summary>
        /// rowContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowContact;

        /// <summary>
        /// litContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litContact;

        /// <summary>
        /// rowEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowEmail;

        /// <summary>
        /// litEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmail;

        /// <summary>
        /// imgAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatar;
    }
}
