//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class HobbiesSection
    {
        /// <summary>
        /// rptHobbies control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptHobbies;

        /// <summary>
        /// pnlNoHobbies control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoHobbies;
    }
}
