//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class SkillsSection
    {
        /// <summary>
        /// rptSkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSkills;

        /// <summary>
        /// pnlNoSkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoSkills;
    }
}
