//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class SocialLinksSection
    {
        /// <summary>
        /// pnlConnect control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlConnect;

        /// <summary>
        /// rptSocialLinks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSocialLinks;
    }
}
