//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class SummarySection
    {
        /// <summary>
        /// pnlSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        /// <summary>
        /// litSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSummary;
    }
}
