//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class UserMenu
    {
        /// <summary>
        /// imgAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatar;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmail;

        /// <summary>
        /// litBio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBio;

        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;

        /// <summary>
        /// lnkViewPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkViewPortfolio;

        /// <summary>
        /// lnkEditDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkEditDetails;

        /// <summary>
        /// lnkSignOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkSignOut;
    }
}
