//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User.Controls
{
    public partial class UserMenu
    {
        /// <summary>
        /// imgAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatar;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmail;

        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;

        /// <summary>
        /// phEditAccountBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEditAccountBtn;

        /// <summary>
        /// lnkViewPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkViewPortfolio;

        /// <summary>
        /// lnkEditDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkEditDetails;

        /// <summary>
        /// lnkEditPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkEditPortfolio;

        /// <summary>
        /// lnkSignOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkSignOut;

        /// <summary>
        /// pnlUserAccountModalMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUserAccountModalMsg;

        /// <summary>
        /// litUserAccountModalMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserAccountModalMsg;

        /// <summary>
        /// txtAccountFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountFirstName;

        /// <summary>
        /// txtAccountLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountLastName;

        /// <summary>
        /// txtAccountEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountEmail;

        /// <summary>
        /// phAdminOnlyAccountFields control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminOnlyAccountFields;

        /// <summary>
        /// ddlAccountRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAccountRole;

        /// <summary>
        /// chkAccountIsActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkAccountIsActive;

        /// <summary>
        /// txtAccountNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountNewPassword;

        /// <summary>
        /// txtAccountConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountConfirmPassword;

        /// <summary>
        /// btnSaveUserAccount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveUserAccount;
    }
}
