//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User
{
    public partial class Dashboard
    {
        /// <summary>
        /// imgAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatar;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmail;

        /// <summary>
        /// litBio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBio;

        /// <summary>
        /// lnkAdminDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkAdminDashboard;

        /// <summary>
        /// lnkViewPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkViewPortfolio;
    }
}
