//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User
{
    public partial class Onboarding
    {
        /// <summary>
        /// onboardingForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm onboardingForm;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// lblErrorMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorMessage;

        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>
        /// lblSuccessMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSuccessMessage;

        /// <summary>
        /// pnlAdminBanner control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAdminBanner;

        /// <summary>
        /// litAdminTargetUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAdminTargetUserName;

        /// <summary>
        /// lnkReturnToAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkReturnToAdmin;

        /// <summary>
        /// litPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>
        /// litPageSubtitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageSubtitle;

        /// <summary>
        /// hfTargetUserId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfTargetUserId;

        /// <summary>
        /// hfCurrentStep control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentStep;

        /// <summary>
        /// hfExistingImagePath control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfExistingImagePath;

        /// <summary>
        /// imgProfilePreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgProfilePreview;

        /// <summary>
        /// fileProfileImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fileProfileImage;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// txtBirthday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBirthday;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// txtContactEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;

        /// <summary>
        /// txtContactNum control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactNum;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// btnSaveStep1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveStep1;

        /// <summary>
        /// hfEducationsJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEducationsJson;

        /// <summary>
        /// btnSaveStep2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveStep2;

        /// <summary>
        /// hfSkillsJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSkillsJson;

        /// <summary>
        /// btnSaveStep3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveStep3;

        /// <summary>
        /// hfAffiliationsJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfAffiliationsJson;

        /// <summary>
        /// hfHobbiesJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfHobbiesJson;

        /// <summary>
        /// btnSaveStep4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveStep4;

        /// <summary>
        /// hfSocialLinksJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSocialLinksJson;

        /// <summary>
        /// btnSaveStep5 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveStep5;

        /// <summary>
        /// btnCompleteOnboarding control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCompleteOnboarding;
    }
}
