//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User
{
    public partial class Onboarding
    {
        /// <summary>
        /// onboardingForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm onboardingForm;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// lblErrorMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorMessage;

        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>
        /// lblSuccessMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSuccessMessage;

        /// <summary>
        /// hfCurrentStep control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentStep;

        /// <summary>
        /// hfExistingImagePath control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfExistingImagePath;

        /// <summary>
        /// imgProfilePreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgProfilePreview;

        /// <summary>
        /// fileProfileImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fileProfileImage;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// txtBirthday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBirthday;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// txtContactEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;

        /// <summary>
        /// txtContactNum control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactNum;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// txtCourse1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCourse1;

        /// <summary>
        /// txtUniversity1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUniversity1;

        /// <summary>
        /// txtEduStartYear1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEduStartYear1;

        /// <summary>
        /// txtEduEndYear1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEduEndYear1;

        /// <summary>
        /// txtCourse2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCourse2;

        /// <summary>
        /// txtUniversity2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUniversity2;

        /// <summary>
        /// txtEduStartYear2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEduStartYear2;

        /// <summary>
        /// txtEduEndYear2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEduEndYear2;

        /// <summary>
        /// txtSkill1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkill1;

        /// <summary>
        /// txtSkillDesc1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkillDesc1;

        /// <summary>
        /// txtSkill2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkill2;

        /// <summary>
        /// txtSkillDesc2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkillDesc2;

        /// <summary>
        /// txtSkill3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkill3;

        /// <summary>
        /// txtSkillDesc3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkillDesc3;

        /// <summary>
        /// txtSkill4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkill4;

        /// <summary>
        /// txtSkillDesc4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkillDesc4;

        /// <summary>
        /// txtOrg1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOrg1;

        /// <summary>
        /// txtRole1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRole1;

        /// <summary>
        /// txtOrgStart1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOrgStart1;

        /// <summary>
        /// txtOrgEnd1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOrgEnd1;

        /// <summary>
        /// txtOrg2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOrg2;

        /// <summary>
        /// txtRole2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRole2;

        /// <summary>
        /// txtOrgStart2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOrgStart2;

        /// <summary>
        /// txtOrgEnd2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOrgEnd2;

        /// <summary>
        /// txtHobby1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHobby1;

        /// <summary>
        /// txtHobbyDesc1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHobbyDesc1;

        /// <summary>
        /// txtHobby2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHobby2;

        /// <summary>
        /// txtHobbyDesc2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHobbyDesc2;

        /// <summary>
        /// txtGithubLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGithubLink;

        /// <summary>
        /// txtLinkedinLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLinkedinLink;

        /// <summary>
        /// txtWebsiteLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtWebsiteLink;

        /// <summary>
        /// txtTwitterLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTwitterLink;

        /// <summary>
        /// txtOtherSocialLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOtherSocialLink;

        /// <summary>
        /// btnCompleteOnboarding control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCompleteOnboarding;
    }
}
