//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User
{
    public partial class Portfolio
    {
        /// <summary>
        /// litPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>
        /// portfolioForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm portfolioForm;

        /// <summary>
        /// litBrandInitials control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBrandInitials;

        /// <summary>
        /// litBrandName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBrandName;

        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;

        /// <summary>
        /// lnkEditPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkEditPortfolio;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// rowAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowAddress;

        /// <summary>
        /// litAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAddress;

        /// <summary>
        /// rowEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowEmail;

        /// <summary>
        /// litEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmail;

        /// <summary>
        /// rowContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowContact;

        /// <summary>
        /// litContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litContact;

        /// <summary>
        /// rowBirthday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel rowBirthday;

        /// <summary>
        /// litBirthday control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBirthday;

        /// <summary>
        /// imgAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatar;

        /// <summary>
        /// pnlSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        /// <summary>
        /// litSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSummary;

        /// <summary>
        /// pnlConnect control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlConnect;

        /// <summary>
        /// rptSocialLinks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSocialLinks;

        /// <summary>
        /// rptEducation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptEducation;

        /// <summary>
        /// pnlNoEducation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoEducation;

        /// <summary>
        /// rptSkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSkills;

        /// <summary>
        /// pnlNoSkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoSkills;

        /// <summary>
        /// rptAffiliations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAffiliations;

        /// <summary>
        /// pnlNoAffiliations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAffiliations;

        /// <summary>
        /// rptHobbies control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptHobbies;

        /// <summary>
        /// pnlNoHobbies control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoHobbies;

        /// <summary>
        /// litFooterName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFooterName;
    }
}
