//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241611JalopPersonalWebsite.Frontend.User
{
    public partial class Portfolio
    {
        /// <summary>
        /// litPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>
        /// portfolioForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm portfolioForm;

        /// <summary>
        /// lnkBrand control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBrand;

        /// <summary>
        /// litBrandInitials control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBrandInitials;

        /// <summary>
        /// litBrandName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBrandName;

        /// <summary>
        /// ucUserMenu control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.UserMenu ucUserMenu;

        /// <summary>
        /// lnkGuestSignIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkGuestSignIn;

        /// <summary>
        /// ucHero control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.HeroSection ucHero;

        /// <summary>
        /// ucSummary control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.SummarySection ucSummary;

        /// <summary>
        /// ucEducation control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.EducationSection ucEducation;

        /// <summary>
        /// ucSkills control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.SkillsSection ucSkills;

        /// <summary>
        /// ucAffiliations control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.AffiliationsSection ucAffiliations;

        /// <summary>
        /// ucHobbies control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.HobbiesSection ucHobbies;

        /// <summary>
        /// ucSocialLinks control.
        /// </summary>
        protected global::_241611JalopPersonalWebsite.Frontend.User.Controls.SocialLinksSection ucSocialLinks;

        /// <summary>
        /// litFooterName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFooterName;
    }
}
